export enum TransactionTypePT {
  ENTRY = "ENTRADA",
  EXIT = "SAÍDA",
  TRANSFERENCE = "TRANSFERÊNCIA",
  DEVOLUTION = "DEVOLUÇÃO",
  RESERVE = "RESERVA"
}

export enum TransactionType {
  ENTRY = "ENTRY",
  EXIT = "EXIT",
  TRANSFERENCE = "TRANSFERENCE",
  DEVOLUTION = "DEVOLUTION",
  RESERVE = "RESERVE"
}
